.TH "raleigh-triangle-index/include/blpapi_streamproxy.h" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
raleigh-triangle-index/include/blpapi_streamproxy.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBblpapi_StreamWriter_t\fP) (const char *data, int length, void *stream)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int(* blpapi_StreamWriter_t) (const char *data, int length, void *stream)"

.PP
Definition at line 33 of file blpapi_streamproxy\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
