.TH "blpapi_Datetime_tag" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blpapi_Datetime_tag \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "blpapi_UChar_t \fBparts\fP"
.br
.ti -1c
.RI "blpapi_UChar_t \fBhours\fP"
.br
.ti -1c
.RI "blpapi_UChar_t \fBminutes\fP"
.br
.ti -1c
.RI "blpapi_UChar_t \fBseconds\fP"
.br
.ti -1c
.RI "blpapi_UInt16_t \fBmilliSeconds\fP"
.br
.ti -1c
.RI "blpapi_UChar_t \fBmonth\fP"
.br
.ti -1c
.RI "blpapi_UChar_t \fBday\fP"
.br
.ti -1c
.RI "blpapi_UInt16_t \fByear\fP"
.br
.ti -1c
.RI "blpapi_Int16_t \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 


.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
