.TH "raleigh-triangle-index/include/blpapi_versioninfo.h" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
raleigh-triangle-index/include/blpapi_versioninfo.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <blpapi_call\&.h>\fP
.br
\fC#include <blpapi_defs\&.h>\fP
.br
\fC#include <blpapi_versionmacros\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBLPAPI_EXPORT\fP void \fBblpapi_getVersionInfo\fP (int *majorVersion, int *minorVersion, int *patchVersion, int *buildVersion)"
.br
.ti -1c
.RI "\fBBLPAPI_EXPORT\fP const char * \fBblpapi_getVersionIdentifier\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBBLPAPI_EXPORT\fP const char* blpapi_getVersionIdentifier (void)"

.SS "\fBBLPAPI_EXPORT\fP void blpapi_getVersionInfo (int * majorVersion, int * minorVersion, int * patchVersion, int * buildVersion)"

.SS "Usage "
.PP
C++ usage 
.PP
 C usage 
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
