.TH "blpapi_ManagedPtr_t_" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blpapi_ManagedPtr_t_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBpointer\fP"
.br
.ti -1c
.RI "\fBblpapi_ManagedPtr_t_data_\fP \fBuserData\fP [4]"
.br
.ti -1c
.RI "blpapi_ManagedPtr_ManagerFunction_t \fBmanager\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 


.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
