.TH "blpapi_CorrelationId_t_" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blpapi_CorrelationId_t_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBsize\fP:8"
.br
.ti -1c
.RI "unsigned int \fBvalueType\fP:4"
.br
.ti -1c
.RI "unsigned int \fBclassId\fP:16"
.br
.ti -1c
.RI "unsigned int \fBreserved\fP:4"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   blpapi_UInt64_t \fBintValue\fP"
.br
.ti -1c
.RI "   \fBblpapi_ManagedPtr_t\fP \fBptrValue\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 


.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
