.TH "raleigh-triangle-index/include/blpapi_correlationid.h" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
raleigh-triangle-index/include/blpapi_correlationid.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <blpapi_types\&.h>\fP
.br
\fC#include <blpapi_defs\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBblpapi_ManagedPtr_t_data_\fP"
.br
.ti -1c
.RI "struct \fBblpapi_ManagedPtr_t_\fP"
.br
.ti -1c
.RI "struct \fBblpapi_CorrelationId_t_\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBblpapi_ManagedPtr_t_\fP \fBblpapi_ManagedPtr_t\fP"
.br
.ti -1c
.RI "typedef int(* \fBblpapi_ManagedPtr_ManagerFunction_t\fP) (\fBblpapi_ManagedPtr_t\fP *managedPtr, const \fBblpapi_ManagedPtr_t\fP *srcPtr, int operation)"
.br
.ti -1c
.RI "typedef struct \fBblpapi_CorrelationId_t_\fP \fBblpapi_CorrelationId_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBblpapi_CorrelationId_t_\fP  \fBblpapi_CorrelationId_t\fP"

.SS "typedef int(* blpapi_ManagedPtr_ManagerFunction_t) (\fBblpapi_ManagedPtr_t\fP *managedPtr, const \fBblpapi_ManagedPtr_t\fP *srcPtr, int operation)"

.PP
Definition at line 49 of file blpapi_correlationid\&.h\&.
.SS "typedef struct \fBblpapi_ManagedPtr_t_\fP \fBblpapi_ManagedPtr_t\fP"

.PP
Definition at line 47 of file blpapi_correlationid\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
