.TH "raleigh-triangle-index/examples/BlpThreadUtil.h" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
raleigh-triangle-index/examples/BlpThreadUtil.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pthread\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBloombergLP::Mutex\fP"
.br
.ti -1c
.RI "class \fBBloombergLP::MutexGuard\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBloombergLP\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSLEEP\fP(s)   sleep(s)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SLEEP(s)   sleep(s)"

.PP
Definition at line 29 of file BlpThreadUtil\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
