.TH "raleigh-triangle-index/examples/ContributionsMktdataExample.cpp" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
raleigh-triangle-index/examples/ContributionsMktdataExample.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <blpapi_topiclist\&.h>\fP
.br
\fC#include <blpapi_providersession\&.h>\fP
.br
\fC#include <blpapi_eventdispatcher\&.h>\fP
.br
\fC#include <blpapi_event\&.h>\fP
.br
\fC#include <blpapi_message\&.h>\fP
.br
\fC#include <blpapi_element\&.h>\fP
.br
\fC#include <blpapi_name\&.h>\fP
.br
\fC#include <blpapi_defs\&.h>\fP
.br
\fC#include <blpapi_exception\&.h>\fP
.br
\fC#include <blpapi_topic\&.h>\fP
.br
\fC#include <blpapi_eventformatter\&.h>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <list>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'BlpThreadUtil\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyStream\fP"
.br
.ti -1c
.RI "class \fBMyEventHandler\fP"
.br
.ti -1c
.RI "class \fBContributionsMktdataExample\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::list< \fBMyStream\fP * > \fBMyStreams\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAuthorizationStatus\fP "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::list<\fBMyStream\fP*> \fBMyStreams\fP"

.PP
Definition at line 87 of file ContributionsMktdataExample\&.cpp\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAuthorizationStatus\fP"

.PP
Definition at line 66 of file ContributionsMktdataExample\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 361 of file ContributionsMktdataExample\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
