.TH "raleigh-triangle-index/input.cpp" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
raleigh-triangle-index/input.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'input\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBloggingCallback\fP (\fBblpapi_UInt64_t\fP threadId, int severity, \fBblpapi_Datetime_t\fP timestamp, const char *category, const char *message)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void loggingCallback (\fBblpapi_UInt64_t\fP threadId, int severity, \fBblpapi_Datetime_t\fP timestamp, const char * category, const char * message)"

.PP
Definition at line 36 of file input\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
