.TH "SessionEventHandler" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SessionEventHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventHandler, EventHandler, EventHandler, EventHandler, and EventHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSessionEventHandler\fP (std::vector< Identity > &identities, std::vector< int > &uuids)"
.br
.ti -1c
.RI "bool \fBprocessEvent\fP (const Event &event, Session *session)"
.br
.ti -1c
.RI "\fBSessionEventHandler\fP (std::vector< Identity > &identities, std::vector< int > &uuids, std::vector< std::string > &securities, const std::string &field)"
.br
.ti -1c
.RI "bool \fBprocessEvent\fP (const Event &event, Session *session)"
.br
.ti -1c
.RI "\fBSessionEventHandler\fP (std::vector< Identity > &identities, std::vector< std::string > &tokens, std::vector< std::string > &securities, const std::string &field)"
.br
.ti -1c
.RI "bool \fBprocessEvent\fP (const Event &event, Session *session)"
.br
.ti -1c
.RI "\fBSessionEventHandler\fP (std::vector< Identity > &identities, std::vector< std::string > &tokens)"
.br
.ti -1c
.RI "bool \fBprocessEvent\fP (const Event &event, Session *session)"
.br
.ti -1c
.RI "\fBSessionEventHandler\fP (std::vector< Identity > &identities, std::vector< int > &uuids)"
.br
.ti -1c
.RI "bool \fBprocessEvent\fP (const Event &event, Session *session)"
.br
.in -1c
.SH "Detailed Description"
.PP 


.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
