.TH "SubscriptionEventHandler" 3 "Wed Apr 13 2016" "Version 1.0.0" "Raleigh Triangle Index" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubscriptionEventHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubscriptionEventHandler\fP (\fBSessionContext\fP *context)"
.br
.ti -1c
.RI "bool \fBprocessEvent\fP (const Event &event, Session *session)"
.br
.in -1c
.SH "Detailed Description"
.PP 


.SH "Author"
.PP 
Generated automatically by Doxygen for Raleigh Triangle Index from the source code\&.
